default_connection_name = "myconnection"

[connections]
[connections.myconnection]
account="zwerczl-jf13932"
user="CLI_USER"
authenticator="SNOWFLAKE_JWT"
role="accountadmin"
database="snowcli"
schema="vd_sandbox"
warehouse="compute_wh"
private_key_file="./rsa_key.p8"
