CREATE OR REPLACE PROCEDURE SNOWCLI.VD_SANDBOX.MY_SPROC2()
RETURNS INT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
    DECLARE
        VAR_BANANA INT DEFAULT 1;
    BEGIN
        RETURN :VAR_BANANA;
    END;
$$
;
